### ISSUE TITLE
Implement deployments by branch in GHA CI workflow

### ISSUE THREAD

**Issue by reactive-firewall** [reactive-firewall/multicast#177]
# GHA Deployment Environments

---

## Context 📃

* GHA Deployments are configured for the project already
  - [x] Deployment -- for release candidates, tags, and stable
  - [x] Testing -- for development branches and release candidates
  - [x] Experimental -- for everything else (that still needs a deployment)
* Environment variables are deployment specific
* GHA triggers differ for different workflows (see #176 for details)

## Goals ⭐ 

* GHA actions should use deployments where appropriate
* Improved application of defence in depth is possible by leveraging environments (albeit only slightly)

---

## Tasks 🗒️ 

- [x] analyze GHA in `.github/workflows/Tests.yml` for alignment with environments
    - [x] BUILD & BOOTSTRAP
    - [x] MATs
    - [x] COVERAGE
    - [x] DOCS
    - [x] INTEGRATION
    - [x] STYLE
    - [ ] EXTRA & other jobs
- [ ] move deployment operations like readthedocs to Deployment environment only
- [x] assign environments as needed

**Comment by reactive-firewall** [comment]
@coderabbitai, please explain how to configure the use of deployments in `.github/workflows/*.yml` configs and then based on the goals of this GHI ( #177 ) walk me through the steps needed to leverage GH Deployments as outlined in this GHI, with specific suggested improvements, and considering the usual project conventions and standards.

**Comment by reactive-firewall** [comment]
@coderabbitai, take a look at https://github.com/reactive-firewall/multicast/actions/runs/12091924700/workflow

**Comment by reactive-firewall** [comment]
@coderabbitai, sure, please help me with applying this environment to specific jobs as well.

**Comment by reactive-firewall** [comment]
what happens when the dynamic environment (`${{ env.ENVIRONMENT }}`) is "Testing"? as in what jobs run in the whole workflow (Tests.yml)? (assuming when they run they are error-free and result in a job status of passing/success)
why or why not?

and if the dynamic environment (`${{ env.ENVIRONMENT }}`) is "Deployment"?

**Comment by reactive-firewall** [comment]
@coderabbitai, let's refactor the entire `.github/workflows/Tests.yml` workflow into separate callable, and reusable workflows;
Namely:
 - separate-out `BUILD` and `BOOTSTRAP` into a separate workflow file called "CI-BUILD.yml"
   - add a set of additional jobs
     - first one that conditionally runs after `BUILD` and `BOOTSTRAP` **both** pass/succeed and sets an output "didBUILD" (a boolean) to true.
     - second one that conditionally runs after **either** `BUILD` or `BOOTSTRAP` fail/error, and conversely sets the output "didBUILD" (a boolean) to false.
   - change BOOTSTRAP to run with the `BUILD` job's actual environment value.
 - separate-out `MATs` into a separate workflow file called "CI-MATs.yml"
   - change the trigger of MATs to `workflow_run` for the new "CI-BUILD.yml" workflow file's workflow, and conditionally on action type compleated, and further conditionally run the MATs based on `didBuild` value
   - Change MATs to use the environment of the triggering completed job (which could be any valid environment type value)
   - Similar to the CI-BUILD pass/fail jobs add conditional jobs (accounting for the variations via the job matrix) for CI-MATs to also add an output boolean 'passedMATs' for the result of the MATs workflow (of-course store-and-forward `didBUILD` too)
 - separate-out the DOCS into it's own workflow file as well
    - DOCs only run in the "Deployment" environment but otherwise are triggered by push events on branches "main", "master" or "stable" and also triggered by pull_request events (namely: create/close/sync/edit/ready_for_review action types)
 - the remaining jobs in Tests.yml will now require COVERAGE and STYLE; COVERAGE and STYLE will both be conditional on the MATs workflow completing and the `passedMATs` from the triggering workflow run. Also COVERAGE will only use Testing/Deployment environments for the upload steps, but can run most other steps in any valid environment value from the triggering MATs run.
 - the remaining jobs in Tests.yml will be changed to use the same environment as the preceeding job's (e.g. COVERAGE's environment -> INTEGRATION/EXTRAS-*/STYLE environment)
 - Similar to COVERAGE, the TOX job will only run conditionally with Testing/Deployment environments.


Due to the large scale of this refactor, please provide each of the entire `.yml`s involved, rather than just the usual focused excerpt of code (this refactor is a special case due to scale)
---
 ALL these changes will of-course require many related adjustments to prevent inter-action dependency regressions and other complications.

**Comment by reactive-firewall** [comment]
info ref: https://docs.github.com/en/actions/sharing-automations/reusing-workflows

**Comment by reactive-firewall** [comment]
@coderabbitai, I pushed some changes, and no BUILD job was triggered by the new `.github/workflows/CI-BUILD.yml` please take a look at all the changes and analyze.

**Comment by reactive-firewall** [comment]
@coderabbitai, check again, on branch "feature-deployments-by-branch-177" namely commit 77b44a614dc9aebf50aae78c595c57435d10b4f1 for the file `.github/workflows/CI-BUILD.yml`

**Comment by reactive-firewall** [comment]
@coderabbitai, please try to simplify the environment variable logic to make it more maintainable (of-course while maintaining it's effective logic)

**Comment by reactive-firewall** [comment]
@coderabbitai, and what about setting the trigger to include any push?

**Comment by reactive-firewall** [comment]
@coderabbitai, I pushed some changes, and no `MATs` job was triggered by the new and successful `.github/workflows/CI-BUILD.yml` completing, please take a look at all the changes on on branch "feature-deployments-by-branch-177" for the files `.github/workflows/CI-*.yml` and analyze.

**Comment by reactive-firewall** [comment]
@codrabbitai, could it be a permissions issue?

**Comment by reactive-firewall** [comment]
@coderabbitai, still no luck, I pushed some changes, but still not triggering "CI-MATs" could it be a permissions issue? Again, no MATs job was triggered by the new and successful .github/workflows/CI-BUILD.yml completing, please take a look at all the changes on branch "feature-deployments-by-branch-177", and look at the file `.github/workflows/CI-MATs.yml` and at the file `.github/workflows/CI-BUILD.yml` and then analyze.

**Comment by reactive-firewall** [comment]
@coderabbitai, still no luck, I pushed another change, but still not triggering "CI-MATs" could it be a permissions issue? Again, no MATs job was triggered by the current and successful .github/workflows/CI-BUILD.yml completing, please take a look at all the changes on branch "feature-deployments-by-branch-177", and look at the file .github/workflows/CI-MATs.yml and at the file .github/workflows/CI-BUILD.yml and then analyze.

I think you might be right on the permissions but can you better explain the "checks" permission and why it is relevant in this case?

also please clarify if these new permissions are needed at the workflow level or if I can add them to the job level instead (e.g. for secure-by-default and defence in depth, and least privileged principles)

**Comment by reactive-firewall** [comment]
@coderabbitai, please verify the complete CI-MATs.yml, and also CI-DOCS.yml
